server:
  port: 80

spring:
  application:
    name:customer-order-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/
  instance:
    instance-id: customer-order-feign

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    com.nong.cloud.order.feign.service.PaymentFeignService: debug

