server:
  port: 10001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10000/eureka

spring:
  profiles:
    active: eureka2