server:
  port: 10000

spring:
  profiles:
    active: eureka1

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10001/eureka

