server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengbinger/config-center
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

## 暴露bus相关端点
management:
  endpoints:  ## 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
