server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengbinger/config-center
