server:
  port: 8001

spring:
  application:
    name: @pom.artifactId@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nong.cloud.payment.entities

eureka:
  client:
    // \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230 eurekaServer \u9ED8\u8BA4\u4E3Atrue
    register-with-eureka: true
    // \u662F\u5426\u4ECEEurekaServer \u6293\u53D6\u5DF2\u6709\u7684\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue\u3002\u5355\u8282\u70B9\u65E0\u6240\u8C13\uFF0C\u96C6\u7FA4\u5FC5\u987B\u8BBE\u7F6E\u4E3Atrue\u624D\u80FD\u914D\u5408ribbon\u4F7F\u7528\u8D1F\u8F7D\u5747\u8861
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10000/eureka
