server:
  port: 8001

spring:
  application:
    name: provider-payment
  datasource:
    # \u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql\u9A71\u52A8\u7C7B
    driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=
        UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.eiletxie.springcloud.entities
    \u5B83\u4E00\u822C\u5BF9\u5E94\u6211\u4EEC\u7684\u5B9E\u4F53\u7C7B\u6240\u5728\u7684\u5305\uFF0C
