server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka,http://localhost:10001/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
logging:
  level:
    com.nong.cloud.order.feign.service.PaymentFeignService: debug
